//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinyMCE_TEXT_ENRICHED.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public int Id { get; set; }
        public string NewsTitle { get; set; }
        public string Content { get; set; }
    }
}
